// Node.js script to generate a static pokemonList.ts file with all Pokémon, sprites, and region info
// Usage: node generatePokemonList.js

import fs from 'fs';
import fetch from 'node-fetch';

const GENERATION_TO_REGION = {
  'generation-i': 'kanto',
  'generation-ii': 'johto',
  'generation-iii': 'hoenn',
  'generation-iv': 'sinnoh',
  'generation-v': 'unova',
  'generation-vi': 'kalos',
  'generation-vii': 'alola',
  'generation-viii': 'galar',
  'generation-ix': 'paldea',
};

async function main() {
  const response = await fetch('https://pokeapi.co/api/v2/pokemon?limit=10000');
  const data = await response.json();
  const results = data.results;

  const pokemonList = [];
  let count = 0;

  for (const poke of results) {
    try {
      const res = await fetch(poke.url);
      const details = await res.json();
      const speciesRes = await fetch(details.species.url);
      const species = await speciesRes.json();
      const gen = species.generation.name;
      const region = GENERATION_TO_REGION[gen];
      if (!region) continue;
      pokemonList.push({
        id: details.id,
        name: details.name,
        sprite: details.sprites.front_default,
        region,
      });
      count++;
      if (count % 50 === 0) console.log(`Fetched ${count} Pokémon...`);
    } catch (e) {
      console.error(`Failed for ${poke.name}:`, e);
    }
  }

  // Write to TypeScript file
  const ts = `// Auto-generated by generatePokemonList.js\nimport type { PokemonOption } from './types';\n\nexport const pokemonList: PokemonOption[] = ${JSON.stringify(pokemonList, null, 2)};\n`;
  fs.writeFileSync('src/data/pokemonList.ts', ts);
  console.log('Done! Wrote src/data/pokemonList.ts');
}

main();
