// Node.js script to generate a static badges.ts file with all badge data for each region
// Usage: node generateBadges.js

import fs from 'fs';
import fetch from 'node-fetch';

const REGION_BADGE_ENDPOINTS = {
  kanto: 1,
  johto: 2,
  hoenn: 3,
  sinnoh: 4,
  unova: 5,
  kalos: 6,
  alola: 7,
  galar: 8,
  paldea: 9,
};

async function main() {
  const badges = [];
  for (const [region, genId] of Object.entries(REGION_BADGE_ENDPOINTS)) {
    try {
      // There is no direct badge endpoint in pokeapi, so you may need to maintain your own badge data or scrape from a reliable source.
      // This script will create a placeholder for each region's badges.
      // You should manually fill in badge names and images for each region.
      for (let i = 1; i <= 8; i++) {
        badges.push({
          id: `${region}-badge-${i}`,
          name: `Badge ${i}`,
          image: `/badges/${region}/badge${i}.png`, // Place badge images in public/badges/{region}/badge{i}.png
          region,
        });
      }
    } catch (e) {
      console.error(`Failed for region ${region}:`, e);
    }
  }

  // Write to TypeScript file
  const ts = `// Auto-generated by generateBadges.js\nimport type { Badge } from './types';\n\nexport const badges: Badge[] = ${JSON.stringify(badges, null, 2)};\n`;
  fs.writeFileSync('src/data/badges.ts', ts);
  console.log('Done! Wrote src/data/badges.ts');
}

main();
