// Auto-generated by generateBadges.js
import type { Badge } from './types';

export const badges: Badge[] = [
  {
    "id": "kanto-badge-1",
    "name": "Badge 1",
    "image": "/badges/kanto/1.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-2",
    "name": "Badge 2",
    "image": "/badges/kanto/2.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-3",
    "name": "Badge 3",
    "image": "/badges/kanto/3.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-4",
    "name": "Badge 4",
    "image": "/badges/kanto/4.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-5",
    "name": "Badge 5",
    "image": "/badges/kanto/5.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-6",
    "name": "Badge 6",
    "image": "/badges/kanto/6.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-7",
    "name": "Badge 7",
    "image": "/badges/kanto/7.png",
    "region": "kanto"
  },
  {
    "id": "kanto-badge-8",
    "name": "Badge 8",
    "image": "/badges/kanto/8.png",
    "region": "kanto"
  },
  {
    "id": "johto-badge-1",
    "name": "Badge 1",
    "image": "/badges/johto/1.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-2",
    "name": "Badge 2",
    "image": "/badges/johto/2.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-3",
    "name": "Badge 3",
    "image": "/badges/johto/3.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-4",
    "name": "Badge 4",
    "image": "/badges/johto/4.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-5",
    "name": "Badge 5",
    "image": "/badges/johto/5.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-6",
    "name": "Badge 6",
    "image": "/badges/johto/6.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-7",
    "name": "Badge 7",
    "image": "/badges/johto/7.png",
    "region": "johto"
  },
  {
    "id": "johto-badge-8",
    "name": "Badge 8",
    "image": "/badges/johto/8.png",
    "region": "johto"
  },
  {
    "id": "hoenn-badge-1",
    "name": "Badge 1",
    "image": "/badges/hoenn/1.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-2",
    "name": "Badge 2",
    "image": "/badges/hoenn/2.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-3",
    "name": "Badge 3",
    "image": "/badges/hoenn/3.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-4",
    "name": "Badge 4",
    "image": "/badges/hoenn/4.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-5",
    "name": "Badge 5",
    "image": "/badges/hoenn/5.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-6",
    "name": "Badge 6",
    "image": "/badges/hoenn/6.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-7",
    "name": "Badge 7",
    "image": "/badges/hoenn/7.png",
    "region": "hoenn"
  },
  {
    "id": "hoenn-badge-8",
    "name": "Badge 8",
    "image": "/badges/hoenn/8.png",
    "region": "hoenn"
  },
  {
    "id": "sinnoh-badge-1",
    "name": "Badge 1",
    "image": "/badges/sinnoh/1.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-2",
    "name": "Badge 2",
    "image": "/badges/sinnoh/2.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-3",
    "name": "Badge 3",
    "image": "/badges/sinnoh/3.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-4",
    "name": "Badge 4",
    "image": "/badges/sinnoh/4.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-5",
    "name": "Badge 5",
    "image": "/badges/sinnoh/5.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-6",
    "name": "Badge 6",
    "image": "/badges/sinnoh/6.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-7",
    "name": "Badge 7",
    "image": "/badges/sinnoh/7.png",
    "region": "sinnoh"
  },
  {
    "id": "sinnoh-badge-8",
    "name": "Badge 8",
    "image": "/badges/sinnoh/8.png",
    "region": "sinnoh"
  },
  {
    "id": "unova-badge-1",
    "name": "Badge 1",
    "image": "/badges/unova/1.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-2",
    "name": "Badge 2",
    "image": "/badges/unova/2.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-3",
    "name": "Badge 3",
    "image": "/badges/unova/3.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-4",
    "name": "Badge 4",
    "image": "/badges/unova/4.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-5",
    "name": "Badge 5",
    "image": "/badges/unova/5.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-6",
    "name": "Badge 6",
    "image": "/badges/unova/6.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-7",
    "name": "Badge 7",
    "image": "/badges/unova/7.png",
    "region": "unova"
  },
  {
    "id": "unova-badge-8",
    "name": "Badge 8",
    "image": "/badges/unova/8.png",
    "region": "unova"
  },
  {
    "id": "kalos-badge-1",
    "name": "Badge 1",
    "image": "/badges/kalos/1.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-2",
    "name": "Badge 2",
    "image": "/badges/kalos/2.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-3",
    "name": "Badge 3",
    "image": "/badges/kalos/3.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-4",
    "name": "Badge 4",
    "image": "/badges/kalos/4.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-5",
    "name": "Badge 5",
    "image": "/badges/kalos/5.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-6",
    "name": "Badge 6",
    "image": "/badges/kalos/6.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-7",
    "name": "Badge 7",
    "image": "/badges/kalos/7.png",
    "region": "kalos"
  },
  {
    "id": "kalos-badge-8",
    "name": "Badge 8",
    "image": "/badges/kalos/8.png",
    "region": "kalos"
  },
  {
    "id": "alola-badge-1",
    "name": "Badge 1",
    "image": "/badges/alola/1.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-2",
    "name": "Badge 2",
    "image": "/badges/alola/2.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-3",
    "name": "Badge 3",
    "image": "/badges/alola/3.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-4",
    "name": "Badge 4",
    "image": "/badges/alola/4.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-5",
    "name": "Badge 5",
    "image": "/badges/alola/5.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-6",
    "name": "Badge 6",
    "image": "/badges/alola/6.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-7",
    "name": "Badge 7",
    "image": "/badges/alola/7.png",
    "region": "alola"
  },
  {
    "id": "alola-badge-8",
    "name": "Badge 8",
    "image": "/badges/alola/8.png",
    "region": "alola"
  },
  {
    "id": "galar-badge-1",
    "name": "Badge 1",
    "image": "/badges/galar/1.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-2",
    "name": "Badge 2",
    "image": "/badges/galar/2.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-3",
    "name": "Badge 3",
    "image": "/badges/galar/3.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-4",
    "name": "Badge 4",
    "image": "/badges/galar/4.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-5",
    "name": "Badge 5",
    "image": "/badges/galar/5.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-6",
    "name": "Badge 6",
    "image": "/badges/galar/6.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-7",
    "name": "Badge 7",
    "image": "/badges/galar/7.png",
    "region": "galar"
  },
  {
    "id": "galar-badge-8",
    "name": "Badge 8",
    "image": "/badges/galar/8.png",
    "region": "galar"
  },
  {
    "id": "paldea-badge-1",
    "name": "Badge 1",
    "image": "/badges/paldea/1.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-2",
    "name": "Badge 2",
    "image": "/badges/paldea/2.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-3",
    "name": "Badge 3",
    "image": "/badges/paldea/3.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-4",
    "name": "Badge 4",
    "image": "/badges/paldea/4.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-5",
    "name": "Badge 5",
    "image": "/badges/paldea/5.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-6",
    "name": "Badge 6",
    "image": "/badges/paldea/6.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-7",
    "name": "Badge 7",
    "image": "/badges/paldea/7.png",
    "region": "paldea"
  },
  {
    "id": "paldea-badge-8",
    "name": "Badge 8",
    "image": "/badges/paldea/8.png",
    "region": "paldea"
  }
];
